// This file was generated by counterfeiter
package provisionerfakes

import (
	"database/sql"
	"sync"

	"github.com/hpcloud/sidecar-extensions/go/extension/mysql/provisioner"
)

type FakeMySQLProvisioner struct {
	IsDatabaseCreatedStub        func(string) (bool, error)
	isDatabaseCreatedMutex       sync.RWMutex
	isDatabaseCreatedArgsForCall []struct {
		arg1 string
	}
	isDatabaseCreatedReturns struct {
		result1 bool
		result2 error
	}
	IsUserCreatedStub        func(string) (bool, error)
	isUserCreatedMutex       sync.RWMutex
	isUserCreatedArgsForCall []struct {
		arg1 string
	}
	isUserCreatedReturns struct {
		result1 bool
		result2 error
	}
	CreateDatabaseStub        func(string) error
	createDatabaseMutex       sync.RWMutex
	createDatabaseArgsForCall []struct {
		arg1 string
	}
	createDatabaseReturns struct {
		result1 error
	}
	DeleteDatabaseStub        func(string) error
	deleteDatabaseMutex       sync.RWMutex
	deleteDatabaseArgsForCall []struct {
		arg1 string
	}
	deleteDatabaseReturns struct {
		result1 error
	}
	QueryStub        func(string, ...interface{}) (*sql.Rows, error)
	queryMutex       sync.RWMutex
	queryArgsForCall []struct {
		arg1 string
		arg2 []interface{}
	}
	queryReturns struct {
		result1 *sql.Rows
		result2 error
	}
	CreateUserStub        func(string, string, string) error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	createUserReturns struct {
		result1 error
	}
	DeleteUserStub        func(string) error
	deleteUserMutex       sync.RWMutex
	deleteUserArgsForCall []struct {
		arg1 string
	}
	deleteUserReturns struct {
		result1 error
	}
}

func (fake *FakeMySQLProvisioner) IsDatabaseCreated(arg1 string) (bool, error) {
	fake.isDatabaseCreatedMutex.Lock()
	fake.isDatabaseCreatedArgsForCall = append(fake.isDatabaseCreatedArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.isDatabaseCreatedMutex.Unlock()
	if fake.IsDatabaseCreatedStub != nil {
		return fake.IsDatabaseCreatedStub(arg1)
	} else {
		return fake.isDatabaseCreatedReturns.result1, fake.isDatabaseCreatedReturns.result2
	}
}

func (fake *FakeMySQLProvisioner) IsDatabaseCreatedCallCount() int {
	fake.isDatabaseCreatedMutex.RLock()
	defer fake.isDatabaseCreatedMutex.RUnlock()
	return len(fake.isDatabaseCreatedArgsForCall)
}

func (fake *FakeMySQLProvisioner) IsDatabaseCreatedArgsForCall(i int) string {
	fake.isDatabaseCreatedMutex.RLock()
	defer fake.isDatabaseCreatedMutex.RUnlock()
	return fake.isDatabaseCreatedArgsForCall[i].arg1
}

func (fake *FakeMySQLProvisioner) IsDatabaseCreatedReturns(result1 bool, result2 error) {
	fake.IsDatabaseCreatedStub = nil
	fake.isDatabaseCreatedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeMySQLProvisioner) IsUserCreated(arg1 string) (bool, error) {
	fake.isUserCreatedMutex.Lock()
	fake.isUserCreatedArgsForCall = append(fake.isUserCreatedArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.isUserCreatedMutex.Unlock()
	if fake.IsUserCreatedStub != nil {
		return fake.IsUserCreatedStub(arg1)
	} else {
		return fake.isUserCreatedReturns.result1, fake.isUserCreatedReturns.result2
	}
}

func (fake *FakeMySQLProvisioner) IsUserCreatedCallCount() int {
	fake.isUserCreatedMutex.RLock()
	defer fake.isUserCreatedMutex.RUnlock()
	return len(fake.isUserCreatedArgsForCall)
}

func (fake *FakeMySQLProvisioner) IsUserCreatedArgsForCall(i int) string {
	fake.isUserCreatedMutex.RLock()
	defer fake.isUserCreatedMutex.RUnlock()
	return fake.isUserCreatedArgsForCall[i].arg1
}

func (fake *FakeMySQLProvisioner) IsUserCreatedReturns(result1 bool, result2 error) {
	fake.IsUserCreatedStub = nil
	fake.isUserCreatedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeMySQLProvisioner) CreateDatabase(arg1 string) error {
	fake.createDatabaseMutex.Lock()
	fake.createDatabaseArgsForCall = append(fake.createDatabaseArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.createDatabaseMutex.Unlock()
	if fake.CreateDatabaseStub != nil {
		return fake.CreateDatabaseStub(arg1)
	} else {
		return fake.createDatabaseReturns.result1
	}
}

func (fake *FakeMySQLProvisioner) CreateDatabaseCallCount() int {
	fake.createDatabaseMutex.RLock()
	defer fake.createDatabaseMutex.RUnlock()
	return len(fake.createDatabaseArgsForCall)
}

func (fake *FakeMySQLProvisioner) CreateDatabaseArgsForCall(i int) string {
	fake.createDatabaseMutex.RLock()
	defer fake.createDatabaseMutex.RUnlock()
	return fake.createDatabaseArgsForCall[i].arg1
}

func (fake *FakeMySQLProvisioner) CreateDatabaseReturns(result1 error) {
	fake.CreateDatabaseStub = nil
	fake.createDatabaseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMySQLProvisioner) DeleteDatabase(arg1 string) error {
	fake.deleteDatabaseMutex.Lock()
	fake.deleteDatabaseArgsForCall = append(fake.deleteDatabaseArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.deleteDatabaseMutex.Unlock()
	if fake.DeleteDatabaseStub != nil {
		return fake.DeleteDatabaseStub(arg1)
	} else {
		return fake.deleteDatabaseReturns.result1
	}
}

func (fake *FakeMySQLProvisioner) DeleteDatabaseCallCount() int {
	fake.deleteDatabaseMutex.RLock()
	defer fake.deleteDatabaseMutex.RUnlock()
	return len(fake.deleteDatabaseArgsForCall)
}

func (fake *FakeMySQLProvisioner) DeleteDatabaseArgsForCall(i int) string {
	fake.deleteDatabaseMutex.RLock()
	defer fake.deleteDatabaseMutex.RUnlock()
	return fake.deleteDatabaseArgsForCall[i].arg1
}

func (fake *FakeMySQLProvisioner) DeleteDatabaseReturns(result1 error) {
	fake.DeleteDatabaseStub = nil
	fake.deleteDatabaseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMySQLProvisioner) Query(arg1 string, arg2 ...interface{}) (*sql.Rows, error) {
	fake.queryMutex.Lock()
	fake.queryArgsForCall = append(fake.queryArgsForCall, struct {
		arg1 string
		arg2 []interface{}
	}{arg1, arg2})
	fake.queryMutex.Unlock()
	if fake.QueryStub != nil {
		return fake.QueryStub(arg1, arg2...)
	} else {
		return fake.queryReturns.result1, fake.queryReturns.result2
	}
}

func (fake *FakeMySQLProvisioner) QueryCallCount() int {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	return len(fake.queryArgsForCall)
}

func (fake *FakeMySQLProvisioner) QueryArgsForCall(i int) (string, []interface{}) {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	return fake.queryArgsForCall[i].arg1, fake.queryArgsForCall[i].arg2
}

func (fake *FakeMySQLProvisioner) QueryReturns(result1 *sql.Rows, result2 error) {
	fake.QueryStub = nil
	fake.queryReturns = struct {
		result1 *sql.Rows
		result2 error
	}{result1, result2}
}

func (fake *FakeMySQLProvisioner) CreateUser(arg1 string, arg2 string, arg3 string) error {
	fake.createUserMutex.Lock()
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.createUserMutex.Unlock()
	if fake.CreateUserStub != nil {
		return fake.CreateUserStub(arg1, arg2, arg3)
	} else {
		return fake.createUserReturns.result1
	}
}

func (fake *FakeMySQLProvisioner) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeMySQLProvisioner) CreateUserArgsForCall(i int) (string, string, string) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return fake.createUserArgsForCall[i].arg1, fake.createUserArgsForCall[i].arg2, fake.createUserArgsForCall[i].arg3
}

func (fake *FakeMySQLProvisioner) CreateUserReturns(result1 error) {
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMySQLProvisioner) DeleteUser(arg1 string) error {
	fake.deleteUserMutex.Lock()
	fake.deleteUserArgsForCall = append(fake.deleteUserArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.deleteUserMutex.Unlock()
	if fake.DeleteUserStub != nil {
		return fake.DeleteUserStub(arg1)
	} else {
		return fake.deleteUserReturns.result1
	}
}

func (fake *FakeMySQLProvisioner) DeleteUserCallCount() int {
	fake.deleteUserMutex.RLock()
	defer fake.deleteUserMutex.RUnlock()
	return len(fake.deleteUserArgsForCall)
}

func (fake *FakeMySQLProvisioner) DeleteUserArgsForCall(i int) string {
	fake.deleteUserMutex.RLock()
	defer fake.deleteUserMutex.RUnlock()
	return fake.deleteUserArgsForCall[i].arg1
}

func (fake *FakeMySQLProvisioner) DeleteUserReturns(result1 error) {
	fake.DeleteUserStub = nil
	fake.deleteUserReturns = struct {
		result1 error
	}{result1}
}

var _ provisioner.MySQLProvisioner = new(FakeMySQLProvisioner)
